### ISSUE TITLE
First Contact

### ISSUE THREAD

**Issue by Mi-Zel** [TIS2024-FMFI/telescope-safety#1]
Find the date for first meeting in Modra.

**Comment by pavelpetrovic** [comment]
Napísali ste doc. Paulechovi? So zvyšnými dvoma skupinami máme prdbežne naplánovaný štvrtok okolo obeda, ale oni idú robiť trochu iné veci, ale s tým istým teleskopom, takže možno by sa to dalo spojiť a ísť tam všetci naraz, ak môžete vtedy. Dohodnite sa priamo s nimi, prosím.
