### ISSUE TITLE
UML component diagram

### ISSUE THREAD

**Issue by Mi-Zel** [TIS2024-FMFI/telescope-safety#12]

**Comment by JanRZ003** [comment]
https://app.moqups.com/ODL6gzYUGj5ToJteLveobY50rU1UNt5Y/view/page/a9fa4ea76

**Comment by JanRZ003** [comment]
https://app.moqups.com/ftSOE8QlgPedWDa9jcwfpW9FDEeekftA/edit/page/ab0c2effe
<img width="613" alt="komponent diagram" src="https://github.com/user-attachments/assets/940faa0a-117b-4622-8d51-2fd1232b3cd9">
