### ISSUE TITLE
Send notes

### ISSUE THREAD

**Issue by Mi-Zel** [TIS2024-FMFI/telescope-safety#2]
Send notes from first meeting to stakeholders

**Comment by pavelpetrovic** [comment]
niekam privesujem moje poznamky zo stretnutia:

- vsetci pritomni
- issues ok, malo by sa uz pracovat na navrhu pripadne implementacii, vidim, ze issues na navrh su povytvarane ✔
- mame finalny draft KP, treba ho odoslat zadavatelovi, aby ho dokladne skontroloval a napisal, co mu tam chyba alebo nesedi
- zapisnica zo stretnutia je v poriadku, mozete pokojne aj podrobnejsie
- vo stvrtok okolo 16 planujeme test vsetkych aktualne dostupnych HW komponentov

**Comment by pavelpetrovic** [comment]
28.10.				
vsetci pritomni				
v zapisnici mi chyba kto ma co na starosti z hladiska navrhu				
nezabudnut na navrh pouzivatelskeho rozhrania				
pripraveny hardver na testovanie, je potrebny intenzivnejsi prieskum technologii - webserver? radio? displej?				
su zvolene vsetky implementacne platformy? moze sa zacat nieco programovat?
