### ISSUE TITLE
Create KP

### ISSUE THREAD

**Issue by Mi-Zel** [TIS2024-FMFI/telescope-safety#3]

**Comment by Mi-Zel** [comment]
https://liveuniba-my.sharepoint.com/:w:/g/personal/zelenak28_uniba_sk/EXTNMoed8f1HsGGeEWJmrycB9gHAm-5JSt1_yY-J9_UQNg?e=98Lctv

**Comment by pavelpetrovic** [comment]
Ahojte, urobil som rôzne úpravy v KP, prosím najskôr si to celé dôkladne prečítajte a potom navrhnite Vaše prípadné úpravy, ak sa s niečím nestotožňujete, tak aby sme dospeli ku vzájomne prijateľnej verzii.  
(v časti s odkazmi som niektoré veci, ktoré tam myslím netreba uvádzať, preškrtol - aby som ich hneď nevymazával, ale je to myslené tak, že sú na vymazanie). 

V týchto troch projektoch, ktoré bežia s hvezdárňou, ma prosím berte a akceptujte trochu ako člena tímu, nielen ako cvičiaceho, lebo toto celé úsilie vychádza z našej spolupráce s hvezdárňou, na ktorej sa celkovo podieľame a záleží nám na nej.
