### ISSUE TITLE
Research of available technologies 

### ISSUE THREAD

**Issue by Mi-Zel** [TIS2024-FMFI/telescope-safety#4]
Find usable technologies for implementation.

**Comment by pavelpetrovic** [comment]
túto knižnicu sme testovali:
  https://github.com/ElectronicCats/mpu6050

**Comment by Mi-Zel** [comment]
https://rpishop.cz/orientace-v-prostoru/2100-waveshare-10-dof-imu-sensor-d-gyroskop-akcelerometr-kompasmagnetometr.html

https://rpishop.cz/senzory/1404-waveshare-10-dof-imu-sensor-c-gyroskop-akcelerometr-kompasmagnetometr.html

Myšlienka na preskúmanie: Nešlo by pomocou kompasu kompenzovať odchylky v meraní akcelerometra? Pripadne ich vyhodnocovať a v správnom čase hodnoty resetovať?

**Comment by Mi-Zel** [comment]
Senzory sú závislé na teplote okolia.
Konkrétny príklad jedného senzora je:
Operatívny od -40 do 85 °C
Plná presnosť od 0 do 65 °C

Nakoľko sa nachádzame v otvorenom priestore, potenciálne tu môžu byť vysoké výkyvy teplôt (hlavne negatívne), ktoré by mohli ovplyvniť meranie.

Pri výbere technológií treba pamätať j na fakt, že sa nachádzame v otvorenom priestore, pripadne vyriešiť ohrev komponentov. Na teploty >0. Je možné,  že systém sa bude ohrievať sám spotrebou elektriky. Treba však na túto potenciálnu hrozbu pamätať.

**Comment by pavelpetrovic** [comment]
ano, väčšina senzorov má zabudovaný aj teplomer, ak to bude v uzavretej krabičke, tak už aj to pomôže, lebo si to bude trochu kúriť, ale pridať tam ešte nejaký rezistor, napr. https://techfun.sk/produkt/rezistor-vykonovy-rozne-typy/ povedzme pripojený cez nejaký spínací tranzistor na jednom PWM pine by mohlo príliš nízku teplotu upraviť.

**Comment by Mi-Zel** [comment]
Cele by sa to dalo nasetupovat pomocov RPi (alebo inych obdobnych zariadeni).
RPi5 (alebo nizsia rada) by bolo pripojene k Ethernetu a malo tak pripojenie na siet. Zaroven by si vytvaralo vlastnu bezdrotovu siet, do ktorej by sa pripojil modul, ktory by bol na dalekohlade (RPi Pico W alebo RPi Zero W). Komunikacia by sice bezala na rovnakej frekvencii ako wifi (2.4), ale tato frekvencia stale spada pod radiove vlny, ako je v poziadavkach a ma implementovanu spolahlivu komunikaciu s Collision Avoidance. RPi5 by nasledne sluzilo ako jednoduchy webserver pre zobrazenie informacii a konfiguraciu systemu.

Dalsie mozne riesenie komunikacie je pouzit radio modul [NRF24L01](https://techfun.sk/produkt/nrf24l01-2-4ghz-modul-pre-prenos-udajov/), ktory podporuje full-duplex komunikaciu. Tento modul by sa dal v pripade nedostatocneho vykonu vymenit za vykonnejsi modul, ktory obsahuje zosilovac signalu [NRF24L01 PA/LNA](https://techfun.sk/produkt/nrf24l01-palna-2-4ghz-modul-s-antenou/).
Oba pouzivaju identicku kniznucu a identicky medzikus ([adapter](https://techfun.sk/produkt/adapter-pre-bezdrotovy-modul-nrf24l01/)) pre odladenie napati. Modul ma istu formu ACK. Podla nej si vieme znovu posielanie packetov konfigurovat sami, alebo pouzit moduly z kniznice (modul by sa mal pokusit opakovane zasalt packet 15x). Modul je mozne nastavit na 125 roznych kanalov a v kazdom kanale otvorit pipes na komunikaciu s vlastnymi adresami. Kazdy modul vie mat otvorenych 6 pipe (1 na ACK, takze 5 uzivatelskych). Takto moze byt jedna nastavena na odosielanie a druha na prijimanie dat pre full-duplex komunikaciu.

**Comment by pavelpetrovic** [comment]
Tie moduly, čo píšete, myslím komunikujú na 2.4 GHz, a preto by sa pravdepodobne rušili s Wifi. Dr. Žigo hovoril o frekvencii 868 MHz. Na tom fungujú tie moduly typu LoRa, dal som aj linku na také, čo aj budeme čoskoro mať na otestovanie do katalógu požiadaviek. Zatiaľ verím, že by mali fungovať tak, že naraz môže komunikovať aj viac ako dve zariadenia, takže by sa jednoducho dala dupliklovať riadiaca jednotka, aby mohla byť aj v miestnosti, kde je teleskop - lebo tam podľa mňa treba niečo mať, nikto nebude loziť hore na teleskop, aby to konfiguroval a určite ale chcú mať aj niečo tam, kde je výskumník, takže mi to vychádza, že treba mať dve - ak budú na tej istej "rádiovej sieti", tak môžu byť jednoducho duplikované a navzájom si mirrorovať informácie, ak používateľ nejaké zadá priamo cez jednu z nich. Informácie, ktoré by vysielala inerciálna jednotka by mali zachytiť obe. 
Celkovo hardvér, ktorý je aktuálne vylistovaný v odkazoch, budete mať veľmi čoskoro dostupný na testovanie. K riadiacej jednotke - aby sme zbytočne nepremršťovali cenu by sme asi mohli použiť Raspberry Pi Pico, ktoré komunikuje aj po ethernete - alebo ak by to nebolo dostatočne dobré, tak potom asi Raspberry 4, ale myslím, že bohate bude stačiť 2GB pamäte, lebo pamäť ich dosť premršťuje. To relé by asi malo byť vyvedené ešte von do nejakej inej škatulky, kde bude aj (prerušiteľná) zásuvka na 230V, aby do škatulky s riadiacou jednotkou nešlo priamo 230V.

**Comment by Mi-Zel** [comment]
Rozprávali sme sa s nimi o 2 prijímacích zariadeniach, na čo nám bolo povedané,  že chcú iba jedno v riadiacej miestnosti,  do ktorej budú zaradené 2 drôty z riadenia pohybu na potrebné odpojenie (chcú od nas, len aby na tej jednotke bolo relé)
Majú to teda byť čisto 2 zariadenia: jedno s gyroskopom a druhe s displayom, relé spínačom, ktoré bude navyše zabezpečovať komunikáciu s užívateľskými zariadeniami.

**Comment by pavelpetrovic** [comment]
Ja viem, ved som tam bol, ale myslim si, ze to nemusi byt finalna predstava, diskutovalo sa aj o tejto moznosti pocas diskusie a mne sa zda, ze tie dovody, ktore som napisal, skor hovoria za to riesenie s dvoma. Je to ale vyspecifikovane tak, ze to skoro vobec neovplyvnuje, ci budu dve alebo jedna, len treba dat pozor, aby sa to navzajom nebilo a este aby sa odzrkadlilo na druhu jednotku co pouzivatel vyberie, to nie je tak narocne. Ale tak ako to je vyspecifikovane by to vyhovovalo aj rezimu prace iba s jednou jednotkou a taketo riesenie je elegantne v tom, ze umozni aj dve, ak sa to niekedy bude zdat uzitocne a zaroven umozni prevadzku aj s jednym.

**Comment by pavelpetrovic** [comment]
Zo stretnutia:

- prosim poriadnejsie zapisnice - treba uz pracovat aj na testovacich scenaroch
- neviem, ci som Vam uz ukazoval, ze mame aj alarm sirenu - ktora blika aj sialene vresti, je na 12V, ale mame k nej prevodnik z 5 na 12V, este nam chyba ta powerbanka
- navrhnite svoj komunikacny protokol medzi jednotkami a zdokumentujte ho v navrhu
- treba nakreslit navrh pouzivatelskeho rozhrania
- nasli sme softverovu SPI kniznicu https://github.com/red-scorp/SoftSPIB
- treba zistit ako sa daju prepinat piny na RPI PICO pre HW SPI - lebo su tam osadene viacnasobne alternativy, zrejme nejakym registrom sa to prepina/vybera?
- zatial skusime ist tou cestou, ze vsetky zariadenia budu RPI PICO - bud s ETH modulom pre riadiacu jednotku alebo PICO2 pre inercialnu jednotku, cize k riadiacej by mal byt pripojeny: ETH kabel, radio modem, tlacidla, display s SD kartou, alebo display a SD karta, k inercialnej jednotke iba senzor a radio.  ak s tym budu problemy, tak sa prepneme na ten RPI ZERO s externym modulom pre ETH.
- ten dalsi senzor, co je na ceste je tento https://www.aliexpress.com/item/1005005494956365.html (pridal som ho do zoznamu v KP)
- ja vyskusam modem a displej, Vy vyskusajte web server
- ak chcete stvrtok poobede sa da prist testovat senzory...
