### ISSUE TITLE
Podrobná špecifikácia vonkajších interfaces v návrhu

### ISSUE THREAD

**Issue by JanRZ003** [TIS2024-FMFI/telescope-safety#7]
Definícia komunikácie medzi jednotlivými časťami HW - merač/vysielač, s prijímačom/zobrazovačom;
Čítanie konfiguračného súboru alebo konfiguračného textového inputu do vyhodnocovacej jednotky;
Prijaté dáta zo snímača script odosiela webovej aplikácii na zobrazenie;

**Comment by JanRZ003** [comment]
https://liveuniba-my.sharepoint.com/:w:/g/personal/zubo3_uniba_sk/EfLBIX4dNQhLn51i4BrfRTYBrC_rJ8-KM1KTBPtt0-3zkw?e=4kVjpF

**Comment by Mi-Zel** [comment]
Prosim pokracujte v upravovani tohoto dokumentu uz len v hlavnom issue #5 kde je cely navrh zjednoteny
