### ISSUE TITLE
podrobný dátový model perzistentných údajov, formátov súborov, komunikačných protokolov (návrh)

### ISSUE THREAD

**Issue by JanRZ003** [TIS2024-FMFI/telescope-safety#8]
Diskusia k otázkam:
1. aké a či vôbec uchovávať log nejakých udalostí alebo polôh
2. v akom formáte budú zadávané súradnice v konfiguračných súboroch
3. komunikácia radio frequency

**Comment by zelenakova** [comment]
https://liveuniba-my.sharepoint.com/:w:/r/personal/zelenakova46_uniba_sk/_layouts/15/doc2.aspx?sourcedoc=%7BE382FDD0-9360-49F0-8BEF-7B3C4E2FE53A%7D&file=Document.docx&action=editnew&mobileredirect=true&wdNewAndOpenCt=1729978811646&ct=1729978812050&wdOrigin=OFFICECOM-WEB.START.NEW&wdPreviousSessionSrc=HarmonyWeb&wdPreviousSession=f0ac05ad-1bda-4711-a123-08ac89bec4ea&cid=4a1d0d6a-7d64-4e5d-9503-fa795dc0efc4

**Comment by zelenakova** [comment]
https://liveuniba-my.sharepoint.com/:w:/g/personal/zelenakova46_uniba_sk/EdD9guNgk_BJi-97PE4v5ToBIKUoBDruNFp_e0BxVZosHQ?e=6Wsela

**Comment by Mi-Zel** [comment]
Prosim pokracujte v upravovani tohoto dokumentu uz len v hlavnom issue #5 kde je cely navrh zjednoteny
